kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: gradle:jdk8-openj9
    commands:
      - gradle --no-daemon clean build shadowJar
    environment:
      OOFIE_VERSION: ${DRONE_TAG}
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: dist/*
trigger:
  event:
    - tag