name: OofieWater
version: 0.1
author: TortleWortle
main: wtf.duck.oofiewater.OofieWater
depend: [OofieLib, PlaceholderAPI]
softdepend: [WorldGuard]
commands:
  oofiewater:
    description: Manage oof
    usage: /<command>
    permission: oofiewater.manage
permissions:
  oofiewater.manage:
    description: Manage oofie
    default: op
  oofiewater.scuba:
    description: Bypass oofie
    default: false